# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FNUJlF66s6egd_XMNKmOeHvxe9ShsNBw
"""

import streamlit as st
import pandas as pd
import re
import io
from datetime import datetime, timedelta

# 設定網頁標題
st.set_page_config(page_title="BOM 轉換工具箱", layout="wide")

# --- 側邊欄選單 ---
st.sidebar.title("🛠️ 工具箱選單")
choice = st.sidebar.selectbox("請選擇功能：", ["BOM 比對並轉換 TXT", "其他功能 (待新增)"])

# --- 核心邏輯函數 ---
def count_locations(loc_str):
    if pd.isna(loc_str) or str(loc_str).strip() == "": return 0
    parts = [p.strip() for p in str(loc_str).split(',')]
    total_count = 0
    for part in parts:
        match = re.match(r'([A-Za-z]+)(\d+)-([A-Za-z]*)(\d+)', part)
        if match:
            p1, n1, p2, n2 = match.groups()
            if p1 == p2 and int(n1) <= int(n2):
                total_count += abs(int(n2) - int(n1)) + 1
            else: total_count += 1
        else: total_count += 1
    return total_count

def match_logic(row, df1_ref):
    df2_cpn = str(row['CPN']).strip()
    df2_mpn = str(row['MPN']).strip() if pd.notna(row['MPN']) else ''
    matched_rows = df1_ref[
        (df1_ref['CPN'].astype(str).str.strip() == df2_cpn) &
        (df1_ref['MPN'].astype(str).replace('nan', '').str.strip() == df2_mpn)
    ]
    return matched_rows['IECPN'].iloc[0] if not matched_rows.empty else "NeedCHECK"

def sort_locations(loc_str):
    if loc_str == '--': return ('', 0)
    match = re.match(r'([A-Za-z]+)(\d+)', str(loc_str))
    if match:
        return (match.group(1), int(match.group(2)))
    return (str(loc_str), 0)

# --- 主程式介面 ---
if choice == "BOM 比對並轉換 TXT":
    st.title("📂 BOM 比對與 TXT 自動生成工具")
    st.info("此工具將執行：1. 比對 PNRF 與 客戶BOM -> 2. 自動展開 Location -> 3. 匯出排序後的 TXT 檔")

    # 1. 檔案上傳
    col1, col2 = st.columns(2)
    with col1:
        u1 = st.file_uploader("上傳 Excel 1 (PNRF List) A=CPN, B=MPN, C=IEC PN", type=["xlsx"])
    with col2:
        u2 = st.file_uploader("上傳 Excel 2 (客戶BOM), A=CPN, B=MPN, C=Location", type=["xlsx"])

    pcba_pn = st.text_input("請輸入 PCBA 板號 (將顯示在第一列):", placeholder="例如: PCBA-12345").strip().upper()

    if st.button("執行轉換任務"):
        if u1 and u2 and pcba_pn:
            try:
                # --- Part 1: 比對邏輯 ---
                df1 = pd.read_excel(u1)
                df2 = pd.read_excel(u2)
                df1.columns = ['CPN', 'MPN', 'IECPN'] + list(df1.columns[3:])
                df2.columns = ['CPN', 'MPN', 'Location'] + list(df2.columns[3:])

                # 生成中間結果
                df3 = pd.DataFrame()
                df3['A'] = df2.apply(lambda x: match_logic(x, df1), axis=1)
                df3['B'] = df2['Location'].apply(count_locations)
                df3['C'] = df2['Location']

                # 加入自定義首列
                header_row = pd.DataFrame([[pcba_pn, '1', '']], columns=['A', 'B', 'C'])
                final_df_to_process = pd.concat([header_row, df3], ignore_index=True)

                # --- Part 2: 展開與轉換 TXT ---
                output_data = []
                for _, row in final_df_to_process.iterrows():
                    iecpn = str(row['A'])
                    if iecpn.lower() == 'nan' or not iecpn.strip(): continue

                    loc_raw = str(row['C'])
                    # 處理 Location 展開
                    individual_locs = [l.strip() for l in loc_raw.replace('實', ',').replace('，', ',').split(',')]

                    expanded = []
                    for item in individual_locs:
                        if not item or item.lower() == 'nan':
                            expanded.append('nan')
                            continue
                        m = re.match(r'([A-Za-z]+)(\d+)-([A-Za-z]*)(\d+)', item)
                        if m:
                            p1, n1, p2, n2 = m.groups()
                            if p1 == p2 and int(n1) <= int(n2):
                                for n in range(int(n1), int(n2) + 1): expanded.append(f"{p1}{n}")
                            else: expanded.append(item)
                        else: expanded.append(item)

                    for loc in expanded:
                        output_data.append([
                            0,
                            loc if loc.lower() != 'nan' else '--',
                            iecpn if iecpn.lower() != 'nan' else '--',
                            "1", "-", "-", "-", "-"
                        ])

                # 排序與編號
                out_df = pd.DataFrame(output_data, columns=["SN", "Loc", "IECPN", "C4", "C5", "C6", "C7", "C8"])
                out_df['SortKey'] = out_df['Loc'].apply(sort_locations)
                out_df = out_df.sort_values(by='SortKey').drop(columns='SortKey')
                out_df["SN"] = range(1, len(out_df) + 1)

                # 生成檔名 (台北時間)
                now = datetime.now() + timedelta(hours=8)
                fname = f"{out_df['IECPN'].iloc[0].replace('/','_')}_{now.strftime('%Y%m%d_%H%M')}.txt"

                # 顯示結果與下載
                st.success(f"✅ 轉換成功！檔名：{fname}")
                st.dataframe(out_df.head(20)) # 顯示前20筆預覽

                # 下載按鈕
                txt_buffer = io.StringIO()
                out_df.to_csv(txt_buffer, sep='\t', header=False, index=False)
                st.download_button(
                    label="📥 下載轉換後的 TXT 檔案",
                    data=txt_buffer.getvalue(),
                    file_name=fname,
                    mime="text/plain"
                )

            except Exception as e:
                st.error(f"發生錯誤: {e}")
        else:
            st.warning("請確保檔案已上傳且已輸入板號。")

elif choice == "其他功能 (待新增)":
    st.title("🚧 建設中")
    st.write("請將您的其他程式碼貼給開發者以進行整合。")
