# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FNUJlF66s6egd_XMNKmOeHvxe9ShsNBw
"""

import streamlit as st
import pandas as pd
import re
import io

# 設定網頁標題
st.set_page_config(page_title="BOM 比對工具", layout="wide")
st.title("📂 BOM 比對與數量計算工具")

def count_locations(loc_str):
    """解析 Location 字串並計算數量"""
    if pd.isna(loc_str) or str(loc_str).strip() == "":
        return 0

    parts = [p.strip() for p in str(loc_str).split(',')]
    total_count = 0

    for part in parts:
        match = re.match(r'([A-Za-z]+)(\d+)-([A-Za-z]*)(\d+)', part)
        if match:
            prefix_start = match.group(1)
            num_start = int(match.group(2))
            prefix_end = match.group(3)
            num_end = int(match.group(4))
            if prefix_start == prefix_end and num_start <= num_end:
                total_count += abs(num_end - num_start) + 1
            else:
                total_count += 1
        else:
            total_count += 1
    return total_count

def match_logic(row, df1_ref):
    """比對 CPN 與 MPN 並返回 IECPN"""
    df2_cpn = str(row['CPN']).strip()
    df2_mpn = str(row['MPN']).strip() if pd.notna(row['MPN']) else ''

    matched_rows = df1_ref[
        (df1_ref['CPN'].astype(str).str.strip() == df2_cpn) &
        (df1_ref['MPN'].astype(str).replace('nan', '').str.strip() == df2_mpn)
    ]

    if not matched_rows.empty:
        return matched_rows['IECPN'].iloc[0]
    else:
        return "NeedCHECK"

# --- 側邊欄：檔案上傳 ---
st.sidebar.header("1. 上傳檔案")
uploaded_file1 = st.sidebar.file_uploader("上傳 Excel 1 (PNRF List)", type=["xlsx"])
uploaded_file2 = st.sidebar.file_uploader("上傳 Excel 2 (客戶 BOM)", type=["xlsx"])

# --- 主要介面：參數輸入 ---
st.header("2. 設定參數")
pcba_pn_input = st.text_input("請輸入 PCBA 板號 (Excel 3 第一列 A 欄資訊):", placeholder="例如: PCBA-ABC-001")
pcba_pn_input = pcba_pn_input.strip().upper()

# --- 處理邏輯 ---
if st.button("開始處理並生成結果"):
    if uploaded_file1 and uploaded_file2 and pcba_pn_input:
        try:
            # 讀取資料
            df1 = pd.read_excel(uploaded_file1)
            df2 = pd.read_excel(uploaded_file2)

            # 重新命名欄位 (根據原程式邏輯)
            df1.columns = ['CPN', 'MPN', 'IECPN'] + list(df1.columns[3:])
            df2.columns = ['CPN', 'MPN', 'Location'] + list(df2.columns[3:])

            # 建立結果
            with st.spinner('正在比對資料中...'):
                df3 = pd.DataFrame()
                df3['Matched_IECPN (A)'] = df2.apply(lambda x: match_logic(x, df1), axis=1)
                df3['Quantity (B)'] = df2['Location'].apply(count_locations)
                df3['Original_Location (C)'] = df2['Location']

                # 建立自定義標題列
                custom_header_row_data = [pcba_pn_input, '1'] + [''] * (len(df3.columns) - 2)
                custom_header_df = pd.DataFrame([custom_header_row_data], columns=df3.columns)
                final_df = pd.concat([custom_header_df, df3], ignore_index=True)

                # 顯示預覽 (前 10 筆)
                st.success("處理完成！")
                st.subheader("結果預覽 (前 10 筆)")
                st.table(final_df.head(10))

                # 準備下載檔案 (使用記憶體緩衝區)
                output = io.BytesIO()
                with pd.ExcelWriter(output, engine='xlsxwriter') as writer:
                    final_df.to_excel(writer, index=False, header=False)

                processed_data = output.getvalue()

                # 下載按鈕
                st.download_button(
                    label="📥 下載 Excel 3 結果檔案",
                    data=processed_data,
                    file_name="Excel_3_Result.xlsx",
                    mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                )
        except Exception as e:
            st.error(f"處理過程發生錯誤: {e}")
    else:
        st.warning("請確保兩個檔案皆已上傳，且已輸入 PCBA 板號。")